# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.ssh.insert_key = false
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provider :virtualbox do |v|
    v.memory = 512
    v.linked_clone = true
  end

  #CentOS
  config.vm.define "centos" do |app|
    app.vm.box = "geerlingguy/centos7"
    app.vm.hostname = "orc-app1.test"
    app.vm.network :private_network, ip: "192.168.60.4"
  end

  #Ubuntu server
  config.vm.define "ubuntu" do |db|
    db.vm.box = "geerlingguy/ubuntu1804"
    db.vm.hostname = "orc-app2.test"
    db.vm.network :private_network, ip: "192.168.60.5"
  end
end
