# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.ssh.insert_key = false
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provider :virtualbox do |v|
    v.memory = 256
  end

  #CentOS
  config.vm.define "rockylinux" do |app|
    app.vm.box = "geerlingguy/rockylinux8"
    app.vm.hostname = "nodejs.test"
    app.vm.network :private_network, ip: "192.168.60.4"
  end

  #Ansible provisioner
  config.vm.provision :ansible do |ansible|
    ansible.playbook = "main.yml"
  end
end
