---
    - name: Ensure Apache is installed.
      package:
        name: "{{ apache_package }}"
        state: present
      register: foo

    - debug: var=foo

    - name: Copy test config file.
      copy:
        src:  test.conf
        dest: "{{ apache_config_dir }}"
      notify: 
        - restart apache

    - name: Make sure handlers are flushed immediately.
      meta: flush_handlers

    - name: Ensure Apache is running and starts at boot.
      service:
        name: "{{ apache_service }}"
        state: started
        enabled: true