#ansible-playbook -i inventory apache.yml
---
- name: Install Apache.
  hosts: all
  become: true

  #vars:
  #  proxy_vars:
  #    http_proxy: http://example-proxy:80/
  #    https_proxy: https://example-proxy:80/

  #vars_files:
  #  - vars/apache_default.yml
  #  - vars/apache_{{ ansible_os_family }}.yml

  handlers:
    - name: restart apache
      service:
        name: "{{ apache_service }}"
        state: restarted

  pre_tasks:
    - debug: var=ansible_os_family
    - name: Load var files.
      include_vars: "{{ item }}"
      with_first_found:
        - "vars/apache_{{ ansible_os_family }}.yml"
        - "vars/apache_default.yml"

  tasks:
    #- name: Add an environment variable to the remote user's shell.
    #  lineinfile:
    #    dest: "~/.bash_profile"
    #    regexp: '^ENV_VAR='
    #    line: 'ENV_VAR=value'
    #  become: false

    #- name: Get the value of an environment variable.
    #  shell: 'source ~/.bash_profile && echo $ENV_VAR' 
    #  register: foo
    #  become: false

    #- debug: msg="The variable is {{ foo.stdout}}"

    #- name: Downlad a file.
    #  get_url:
    #    url: http://ipv4.download.thinkbroadband.com/20MB.zip
    #    dest: /tmp
    #  environment: proxy_vars


    - name: Ensure Apache is installed.
      package:
        name: "{{ apache_package }}"
        state: present
      register: foo

    - debug: var=foo

    - name: Copy test config file.
      copy:
        src:  test.conf
        dest: "{{ apache_config_dir }}"
      notify: 
        - restart apache

    - name: Make sure handlers are flushed immediately.
      meta: flush_handlers

    - name: Ensure Apache is running and starts at boot.
      service:
        name: "{{ apache_service }}"
        state: started
        enabled: true
